#!/usr/bin/expect
#tcl scripts - ajuste tela switches huawei, hp ou 3com
### 100% working ###

#declaracao de variaveis
set timeout 3
set ip [lindex $argv 0]
#set name [lindex $argv 1]
#set port [lindex $argv 2]
#set user [lindex $argv 3]
#set password [lindex $argv 4]
set password @2019ig3sDF!
set user igesdf
set server 10.85.70.24
set date 26122018

#inicio do script
spawn telnet $ip
sleep 2;
expect "Username:";
send "$user\r";
expect "Password:";
send "$password\r";
expect ">";
send "system-view\r";
expect "]";
send "local-user ihbdf\r";
expect "]";
send "password cipher nova2018\r";
expect "]";
send "authorization-attribute level 3\r";
expect "]";
send "level 3\r";
expect "]";
send "service-type ssh telnet terminal\r";
expect "]";
send "quit\r";
expect ">";
send "quit\r";


#interact

