#!/usr/bin/expect
#tcl scripts - ajuste de banner switches huawei, hp ou 3com
### 100% working ###

#declaracao de variaveis
set timeout 3
set ip [lindex $argv 0]
#set name [lindex $argv 1]
#set port [lindex $argv 2]
#set user [lindex $argv 3]
#set password [lindex $argv 4]
set password nova2018
set user ihbdf

#inicio do script
spawn telnet $ip
sleep 2;
expect "Username:";
send "$user\r";
expect "Password:";
send "$password\r";
expect ">";
send "system-view\r";
expect "]";
send "undo header incoming\r";
expect "]";
send "undo header motd\r";
expect "]";
send "header login %#########################################################\r";
send "#                                                       #\r";
send "#   IGESDF - Instituto de Gestao Estrategica de Saude   #\r";
send "#             do Distrito Federal.                      #\r";
send "#                                                       #\r";
send "#                                                       #\r";
send "#  Acesso permitido somente a pessoas autorizadas.      #\r";
send "#  Caso nao seja usuario autorizado, desconecte-se      #\r";
send "#  imediatamente, respeitando as regras da empresa e a  #\r";
send "#  legislacao em vigor.                                 #\r";
send "#  O uso improprio ou nao autorizado deste sistema      #\r";
send "#  resultara em acoes disciplinares administrativas,    #\r";
send "#  civis e criminais.                                   #\r";
send "#  Continuando a utilizacao deste sistema, voce indica  #\r";
send "#  sua consciencia e consentimento com esses termos e   #\r";
send "#  condicoes de uso.                                    #\r";
send "#                                                       #\r";
send "#########################################################%\r";
expect "%";
send "\r";
expect "]";
send "quit\r";
expect ">";
send "quit\r";

