#!/usr/bin/expect
#tcl scripts para rede - salva config
### 100% working ###

#declaracao de variaveis
set timeout 3
set ip [lindex $argv 0]
#set name [lindex $argv 1]
#set port [lindex $argv 2]
#set user [lindex $argv 3]
#set password [lindex $argv 4]
set password nova2018
set user ihbdf

#inicio do script
spawn telnet $ip
sleep 2;
expect "Username:";
send "$user\r";
expect "Password:";
send "$password\r";
expect ">";
send "save\r";
expect ":"
send "y\r";
expect ":";
send "\r";
expect ":"
send "y\r";
sleep 30;
expect "success";
send "quit\r";
#interact

