#!/usr/bin/expect
#tcl scripts - ajuste de banner switches huawei, hp ou 3com
### 100% working ###

#declaracao de variaveis
set timeout 3
set count 28
set ip [lindex $argv 0]
#set name [lindex $argv 1]
#set port [lindex $argv 2]
#set user [lindex $argv 3]
#set password [lindex $argv 4]
set password nova2018
set user ihbdf

#inicio do script
spawn telnet $ip
sleep 2;
expect "Username:";
send "$user\r";
expect "Password:";
send "$password\r";
expect ">";
send "system-view\r";
expect "]";
while {$count > 0 } {
send "interface GigabitEthernet 1\/0\/$count\n";
expect "]";
send "stp edged-port\n";
expect "]";
send "interface Ethernet 1\/0\/$count\n";
expect "]";
send "stp edged-port\n";
expect "]";
set count [expr $count-1];
}
expect "]";
send "quit\r";
expect ">";
send "quit\r";

